export const s04_1 = `Need to install the following packages:
create-next-app@12.3.1
Ok to proceed? (y) y
√ What is your project named? ... test-app
√ Would you like to use ESLint with this project? ... No / Yes
√ Would you like to use Tailwind CSS with this project? ... No / Yes`;

export const s04_2 = `/// <reference path="../node_modules/@geovistory/design-system-web/dist/types/react.d.ts" />
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { defineCustomElements } from '@geovistory/design-system-web/loader';

// Here we define the web components (custom elements)
defineCustomElements();

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
`;

export const s04_3 = `...
<main>
  <ion-card>
    <ion-card-header>
      <ion-card-subtitle>Class of entity i315800</ion-card-subtitle>
      <ion-card-title>
        <geov-entity-class-label
          sparql-endpoint="https://sparql.geovistory.org/api_v1_community_data"
          entity-id="i315800"
        ></geov-entity-class-label>
      </ion-card-title>
    </ion-card-header>
  </ion-card>
</main>
...`;

export const s04_4 = `import { renderToString } from '@geovistory/design-system-web/hydrate';
import type { JSXElementConstructor, ReactElement } from 'react';
import ReactDOMServer from 'react-dom/server';
import { Window } from 'happy-dom';
export async function serverRender(
  element: ReactElement<any, string | JSXElementConstructor<any>>
) {
  const html = ReactDOMServer.renderToString(element);
  let serverFetchedData: any;
  const stencilHydrateOutput = await renderToString(html, {
    removeHtmlComments: true,
    beforeHydrate: (doc) => {
      doc.__STENCIL_DATA__ = {};
    },
    afterHydrate: (doc) => {
      serverFetchedData = doc.__STENCIL_DATA__;
    },
  });

  const happyDomWindow = new Window();
  const happyDomDoc = happyDomWindow.document;
  happyDomDoc.write(stencilHydrateOutput.html);
  const bodyInnerHtml = happyDomDoc.querySelector('body').getInnerHTML();
  const headInnerHtml = happyDomDoc.querySelector('head').getInnerHTML();
  return { bodyInnerHtml: bodyInnerHtml, headInnerHtml, serverFetchedData };
}`;

export const s04_5 = `import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { serverRender } from '../lib/serverRender';
import styles from '../styles/Home.module.css';

interface HomeProps {
  _ssrHtmlBody: string;
  _ssrHtmlHead: string;
}

const Home: NextPage<HomeProps> = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        dangerouslySetInnerHTML={{ __html: props._ssrHtmlBody }}
      ></main>
    </div>
  );
};

const ssr = () => (
  <ion-card>
    <ion-card-header>
      <ion-card-subtitle>Class of entity i315800</ion-card-subtitle>
      <ion-card-title>
        <geov-entity-class-label
          sparql-endpoint="https://sparql.geovistory.org/api_v1_community_data"
          entity-id="i315800"
        ></geov-entity-class-label>
      </ion-card-title>
    </ion-card-header>
  </ion-card>
);

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const res = await serverRender(ssr());

  return {
    props: {
      _ssrHtmlBody: res.bodyInnerHtml,
      _ssrHtmlHead: res.headInnerHtml,
    },
    revalidate: 10,
  };
};

export default Home;
`;

export const s04_6 = `...
import { getSSRData } from '../../lib/ssr/getSSRData';
import { setSSRData } from '../../lib/ssr/setSSRData';
import { setSSRId } from '../../lib/ssr/setSSRId';
...

export class GeovEntityClassLabel {
  @Prop({ reflect: true }) _ssrId?: string;         // <- declares an _ssrId property that is reflected as attribute

  @State() data?: GeovClassLabelData;               // <- declares data as state

  constructor() {
    setSSRId(this);                                 // <- assigns an id to the component
  }

  async componentWillLoad() {

    this.data = getSSRData(this._ssrId);            // <- try to get data from ssr

    if (!this.data) {                               // <- if no data found...
      ...
      await this.fetchData()                        // <- fetchData on client side
        .then(d => {
          this.data = d;
          setSSRData(this._ssrId, d);
          return d;
        })
        .catch(d => {
          this.data = d;
          return d;
        });
    }
  }
 ...
}
`;

export const s04_7 = `export const setSSRId = (component: { _ssrId?: string }) => {
  // @ts-ignore
  if (document?.__STENCIL_DATA__ && !component._ssrId) {
    component._ssrId = generateUID();
  }
};`;

export const s04_8 = `export function getSSRData(key: string): any {
  if (key) {
    // @ts-ignore
    return window?.__NEXT_DATA__?.props?.pageProps?._ssrData?.[key];
  }
}`;

export const s04_9 = `export function setSSRData(key: string, val: any) {
  // @ts-ignore
  if (typeof document?.__STENCIL_DATA__ === 'object') document.__STENCIL_DATA__[key] = val;
}`;

export const s04_10 = `export async function serverRender(
 ...
  const stencilHydrateOutput = await renderToString(html, {
    removeHtmlComments: true,
    beforeHydrate: (doc) => {
      doc.__STENCIL_DATA__ = {};                  // <- Make document.__STENCIL_DATA__ an object
    },
    afterHydrate: (doc) => {
      serverFetchedData = doc.__STENCIL_DATA__;   // <- document.__STENCIL_DATA__ contains fetched data
    },
  });

  return { bodyInnerHtml: bodyInnerHtml, headInnerHtml, serverFetchedData }; // <- return fetched data
}`;

export const s04_11 = `...
interface HomeProps {
  _ssrHtmlBody: string;
  _ssrHtmlHead: string;
  _ssrData: { [key: string]: any };         <- add this line
}
...
export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const res = await serverRender(ssr());

  return {
    props: {
      _ssrHtmlBody: res.bodyInnerHtml,
      _ssrHtmlHead: res.headInnerHtml,
      _ssrData: res.serverFetchedData        <- add this line
    },
    revalidate: 10,
  };
};
...
`;
