/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface GvButton {
    }
    interface GvPerson {
        "birthdate": string;
        "lastname": string;
        "name": string;
    }
}
declare global {
    interface HTMLGvButtonElement extends Components.GvButton, HTMLStencilElement {
    }
    var HTMLGvButtonElement: {
        prototype: HTMLGvButtonElement;
        new (): HTMLGvButtonElement;
    };
    interface HTMLGvPersonElement extends Components.GvPerson, HTMLStencilElement {
    }
    var HTMLGvPersonElement: {
        prototype: HTMLGvPersonElement;
        new (): HTMLGvPersonElement;
    };
    interface HTMLElementTagNameMap {
        "gv-button": HTMLGvButtonElement;
        "gv-person": HTMLGvPersonElement;
    }
}
declare namespace LocalJSX {
    interface GvButton {
    }
    interface GvPerson {
        "birthdate"?: string;
        "lastname"?: string;
        "name"?: string;
    }
    interface IntrinsicElements {
        "gv-button": GvButton;
        "gv-person": GvPerson;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gv-button": LocalJSX.GvButton & JSXBase.HTMLAttributes<HTMLGvButtonElement>;
            "gv-person": LocalJSX.GvPerson & JSXBase.HTMLAttributes<HTMLGvPersonElement>;
        }
    }
}
