/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GeovButton {
        "geovStyle": string;
        "ghost": boolean;
        "href"?: string;
        "leftIcon": string;
        "outline": boolean;
        "rightIcon": string;
        "rounded": boolean;
        "solid": boolean;
    }
    interface GeovCard {
        "geovStyle": string;
        "height": string;
        "justify": 'start' | 'end' | 'center' | 'space-around' | 'space-between';
        "width": string;
    }
    interface GeovCarousel {
        "height": string;
        "interval": number;
        "transition": number;
        "width": string;
    }
    interface GeovColumn {
        "alignCenter": boolean;
        "alignEnd": boolean;
        "alignStart": boolean;
        "center": boolean;
        "end": boolean;
        "fh": boolean;
        "fw": boolean;
        "geovStyle": string;
        "spaceAround": boolean;
        "spaceBetween": boolean;
        "start": boolean;
    }
    interface GeovCompanyCard {
        "description": string;
        "geovStyle": string;
        "imageUrl": string;
        "name": string;
        "websiteUrl": string;
    }
    interface GeovDivider {
        "geovStyle": string;
        "height": string;
        "horizontal": boolean;
        "vertical": boolean;
        "width": string;
    }
    interface GeovFooterGeovistory {
        "featuredProjects": string;
        "geovStyle": string;
    }
    interface GeovHeading {
        "geovStyle": string;
        "h1": boolean;
        "h2": boolean;
        "h3": boolean;
        "light": boolean;
    }
    interface GeovIcon {
        "arrowRight": boolean;
        "geovStyle": string;
        "github": boolean;
        "large": boolean;
        "link": boolean;
        "medium": boolean;
        "small": boolean;
    }
    interface GeovLink {
        "geovStyle": string;
        "grey": boolean;
        "href": string;
        "light": boolean;
    }
    interface GeovLogo {
        "geovStyle": string;
        "geovistory": boolean;
        "geovistoryWhite": boolean;
    }
    interface GeovNavbar {
        "geovStyle": string;
        "height": string;
        "links": string;
        "login": string;
        "login_href": string;
        "logo": string;
    }
    interface GeovProjectCard {
        "geovStyle": string;
        "projectDesc": string;
        "projectPageUrl": string;
        "projectTitle": string;
    }
    interface GeovRow {
        "alignCenter": boolean;
        "alignEnd": boolean;
        "alignStart": boolean;
        "center": boolean;
        "end": boolean;
        "fh": boolean;
        "fw": boolean;
        "geovStyle": string;
        "spaceAround": boolean;
        "spaceBetween": boolean;
        "start": boolean;
    }
    interface GeovTabs {
    }
    interface GeovText {
        "caption": boolean;
        "center": boolean;
        "description": boolean;
        "end": boolean;
        "geovStyle": string;
        "light": boolean;
        "start": boolean;
        "subtitle": boolean;
        "text": boolean;
    }
}
declare global {
    interface HTMLGeovButtonElement extends Components.GeovButton, HTMLStencilElement {
    }
    var HTMLGeovButtonElement: {
        prototype: HTMLGeovButtonElement;
        new (): HTMLGeovButtonElement;
    };
    interface HTMLGeovCardElement extends Components.GeovCard, HTMLStencilElement {
    }
    var HTMLGeovCardElement: {
        prototype: HTMLGeovCardElement;
        new (): HTMLGeovCardElement;
    };
    interface HTMLGeovCarouselElement extends Components.GeovCarousel, HTMLStencilElement {
    }
    var HTMLGeovCarouselElement: {
        prototype: HTMLGeovCarouselElement;
        new (): HTMLGeovCarouselElement;
    };
    interface HTMLGeovColumnElement extends Components.GeovColumn, HTMLStencilElement {
    }
    var HTMLGeovColumnElement: {
        prototype: HTMLGeovColumnElement;
        new (): HTMLGeovColumnElement;
    };
    interface HTMLGeovCompanyCardElement extends Components.GeovCompanyCard, HTMLStencilElement {
    }
    var HTMLGeovCompanyCardElement: {
        prototype: HTMLGeovCompanyCardElement;
        new (): HTMLGeovCompanyCardElement;
    };
    interface HTMLGeovDividerElement extends Components.GeovDivider, HTMLStencilElement {
    }
    var HTMLGeovDividerElement: {
        prototype: HTMLGeovDividerElement;
        new (): HTMLGeovDividerElement;
    };
    interface HTMLGeovFooterGeovistoryElement extends Components.GeovFooterGeovistory, HTMLStencilElement {
    }
    var HTMLGeovFooterGeovistoryElement: {
        prototype: HTMLGeovFooterGeovistoryElement;
        new (): HTMLGeovFooterGeovistoryElement;
    };
    interface HTMLGeovHeadingElement extends Components.GeovHeading, HTMLStencilElement {
    }
    var HTMLGeovHeadingElement: {
        prototype: HTMLGeovHeadingElement;
        new (): HTMLGeovHeadingElement;
    };
    interface HTMLGeovIconElement extends Components.GeovIcon, HTMLStencilElement {
    }
    var HTMLGeovIconElement: {
        prototype: HTMLGeovIconElement;
        new (): HTMLGeovIconElement;
    };
    interface HTMLGeovLinkElement extends Components.GeovLink, HTMLStencilElement {
    }
    var HTMLGeovLinkElement: {
        prototype: HTMLGeovLinkElement;
        new (): HTMLGeovLinkElement;
    };
    interface HTMLGeovLogoElement extends Components.GeovLogo, HTMLStencilElement {
    }
    var HTMLGeovLogoElement: {
        prototype: HTMLGeovLogoElement;
        new (): HTMLGeovLogoElement;
    };
    interface HTMLGeovNavbarElement extends Components.GeovNavbar, HTMLStencilElement {
    }
    var HTMLGeovNavbarElement: {
        prototype: HTMLGeovNavbarElement;
        new (): HTMLGeovNavbarElement;
    };
    interface HTMLGeovProjectCardElement extends Components.GeovProjectCard, HTMLStencilElement {
    }
    var HTMLGeovProjectCardElement: {
        prototype: HTMLGeovProjectCardElement;
        new (): HTMLGeovProjectCardElement;
    };
    interface HTMLGeovRowElement extends Components.GeovRow, HTMLStencilElement {
    }
    var HTMLGeovRowElement: {
        prototype: HTMLGeovRowElement;
        new (): HTMLGeovRowElement;
    };
    interface HTMLGeovTabsElement extends Components.GeovTabs, HTMLStencilElement {
    }
    var HTMLGeovTabsElement: {
        prototype: HTMLGeovTabsElement;
        new (): HTMLGeovTabsElement;
    };
    interface HTMLGeovTextElement extends Components.GeovText, HTMLStencilElement {
    }
    var HTMLGeovTextElement: {
        prototype: HTMLGeovTextElement;
        new (): HTMLGeovTextElement;
    };
    interface HTMLElementTagNameMap {
        "geov-button": HTMLGeovButtonElement;
        "geov-card": HTMLGeovCardElement;
        "geov-carousel": HTMLGeovCarouselElement;
        "geov-column": HTMLGeovColumnElement;
        "geov-company-card": HTMLGeovCompanyCardElement;
        "geov-divider": HTMLGeovDividerElement;
        "geov-footer-geovistory": HTMLGeovFooterGeovistoryElement;
        "geov-heading": HTMLGeovHeadingElement;
        "geov-icon": HTMLGeovIconElement;
        "geov-link": HTMLGeovLinkElement;
        "geov-logo": HTMLGeovLogoElement;
        "geov-navbar": HTMLGeovNavbarElement;
        "geov-project-card": HTMLGeovProjectCardElement;
        "geov-row": HTMLGeovRowElement;
        "geov-tabs": HTMLGeovTabsElement;
        "geov-text": HTMLGeovTextElement;
    }
}
declare namespace LocalJSX {
    interface GeovButton {
        "geovStyle"?: string;
        "ghost"?: boolean;
        "href"?: string;
        "leftIcon"?: string;
        "outline"?: boolean;
        "rightIcon"?: string;
        "rounded"?: boolean;
        "solid"?: boolean;
    }
    interface GeovCard {
        "geovStyle"?: string;
        "height"?: string;
        "justify"?: 'start' | 'end' | 'center' | 'space-around' | 'space-between';
        "width"?: string;
    }
    interface GeovCarousel {
        "height"?: string;
        "interval"?: number;
        "transition"?: number;
        "width"?: string;
    }
    interface GeovColumn {
        "alignCenter"?: boolean;
        "alignEnd"?: boolean;
        "alignStart"?: boolean;
        "center"?: boolean;
        "end"?: boolean;
        "fh"?: boolean;
        "fw"?: boolean;
        "geovStyle"?: string;
        "spaceAround"?: boolean;
        "spaceBetween"?: boolean;
        "start"?: boolean;
    }
    interface GeovCompanyCard {
        "description"?: string;
        "geovStyle"?: string;
        "imageUrl"?: string;
        "name"?: string;
        "websiteUrl"?: string;
    }
    interface GeovDivider {
        "geovStyle"?: string;
        "height"?: string;
        "horizontal"?: boolean;
        "vertical"?: boolean;
        "width"?: string;
    }
    interface GeovFooterGeovistory {
        "featuredProjects"?: string;
        "geovStyle"?: string;
    }
    interface GeovHeading {
        "geovStyle"?: string;
        "h1"?: boolean;
        "h2"?: boolean;
        "h3"?: boolean;
        "light"?: boolean;
    }
    interface GeovIcon {
        "arrowRight"?: boolean;
        "geovStyle"?: string;
        "github"?: boolean;
        "large"?: boolean;
        "link"?: boolean;
        "medium"?: boolean;
        "small"?: boolean;
    }
    interface GeovLink {
        "geovStyle"?: string;
        "grey"?: boolean;
        "href"?: string;
        "light"?: boolean;
    }
    interface GeovLogo {
        "geovStyle"?: string;
        "geovistory"?: boolean;
        "geovistoryWhite"?: boolean;
    }
    interface GeovNavbar {
        "geovStyle"?: string;
        "height"?: string;
        "links"?: string;
        "login"?: string;
        "login_href"?: string;
        "logo"?: string;
    }
    interface GeovProjectCard {
        "geovStyle"?: string;
        "projectDesc"?: string;
        "projectPageUrl"?: string;
        "projectTitle"?: string;
    }
    interface GeovRow {
        "alignCenter"?: boolean;
        "alignEnd"?: boolean;
        "alignStart"?: boolean;
        "center"?: boolean;
        "end"?: boolean;
        "fh"?: boolean;
        "fw"?: boolean;
        "geovStyle"?: string;
        "spaceAround"?: boolean;
        "spaceBetween"?: boolean;
        "start"?: boolean;
    }
    interface GeovTabs {
    }
    interface GeovText {
        "caption"?: boolean;
        "center"?: boolean;
        "description"?: boolean;
        "end"?: boolean;
        "geovStyle"?: string;
        "light"?: boolean;
        "start"?: boolean;
        "subtitle"?: boolean;
        "text"?: boolean;
    }
    interface IntrinsicElements {
        "geov-button": GeovButton;
        "geov-card": GeovCard;
        "geov-carousel": GeovCarousel;
        "geov-column": GeovColumn;
        "geov-company-card": GeovCompanyCard;
        "geov-divider": GeovDivider;
        "geov-footer-geovistory": GeovFooterGeovistory;
        "geov-heading": GeovHeading;
        "geov-icon": GeovIcon;
        "geov-link": GeovLink;
        "geov-logo": GeovLogo;
        "geov-navbar": GeovNavbar;
        "geov-project-card": GeovProjectCard;
        "geov-row": GeovRow;
        "geov-tabs": GeovTabs;
        "geov-text": GeovText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "geov-button": LocalJSX.GeovButton & JSXBase.HTMLAttributes<HTMLGeovButtonElement>;
            "geov-card": LocalJSX.GeovCard & JSXBase.HTMLAttributes<HTMLGeovCardElement>;
            "geov-carousel": LocalJSX.GeovCarousel & JSXBase.HTMLAttributes<HTMLGeovCarouselElement>;
            "geov-column": LocalJSX.GeovColumn & JSXBase.HTMLAttributes<HTMLGeovColumnElement>;
            "geov-company-card": LocalJSX.GeovCompanyCard & JSXBase.HTMLAttributes<HTMLGeovCompanyCardElement>;
            "geov-divider": LocalJSX.GeovDivider & JSXBase.HTMLAttributes<HTMLGeovDividerElement>;
            "geov-footer-geovistory": LocalJSX.GeovFooterGeovistory & JSXBase.HTMLAttributes<HTMLGeovFooterGeovistoryElement>;
            "geov-heading": LocalJSX.GeovHeading & JSXBase.HTMLAttributes<HTMLGeovHeadingElement>;
            "geov-icon": LocalJSX.GeovIcon & JSXBase.HTMLAttributes<HTMLGeovIconElement>;
            "geov-link": LocalJSX.GeovLink & JSXBase.HTMLAttributes<HTMLGeovLinkElement>;
            "geov-logo": LocalJSX.GeovLogo & JSXBase.HTMLAttributes<HTMLGeovLogoElement>;
            "geov-navbar": LocalJSX.GeovNavbar & JSXBase.HTMLAttributes<HTMLGeovNavbarElement>;
            "geov-project-card": LocalJSX.GeovProjectCard & JSXBase.HTMLAttributes<HTMLGeovProjectCardElement>;
            "geov-row": LocalJSX.GeovRow & JSXBase.HTMLAttributes<HTMLGeovRowElement>;
            "geov-tabs": LocalJSX.GeovTabs & JSXBase.HTMLAttributes<HTMLGeovTabsElement>;
            "geov-text": LocalJSX.GeovText & JSXBase.HTMLAttributes<HTMLGeovTextElement>;
        }
    }
}
